import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Container } from "@mui/material";
import { Header } from "./Header";
import styles from "./styles.module.scss";
import { Content } from "./Content";
import { Footer } from "./Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className={styles.wrapper}>
          <Content>
            <Container>{children}</Container>
          </Content>
          <Footer />
        </div>
      </body>
    </html>
  );
}
