import type { Metadata } from "next";
import "./globals.css";
import { Container } from "@mui/material";
import styles from "./styles.module.scss";
import { inter } from "@/font";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";
import { Footer } from "@/components/layout/footer/Footer";
import { Header } from "@/components/layout/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <Header />
          <div className={styles.wrapper}>
            <Content>
              <Container>{children}</Container>
            </Content>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}

type ContentProps = {
  children: JSX.Element;
};

const Content = ({ children }: ContentProps) => {
  return <div className={styles.page}>{children}</div>;
};
